import json
import os
import re
from inspect import signature
from typing import Any, Dict, List, Literal, Tuple, cast

from llama_index.core.base.llms.types import ChatMessage, ChatResponse, MessageRole
from pydantic import BaseModel

from .debug_memory import DebugMemory
from .log_utils import get_logger
from .prompts import ORDER_PROMPT
from .sim_reviewer import SimReviewer, check_syntax
from .token_counter import TokenCounter, TokenCounterCached
from .utils import reformat_json_string

logger = get_logger(__name__)

SYSTEM_PROMPT = r"""
You are an expert in RTL design.
Your job is to use actions to edit and simulate SystemVerilog rtl_code,
To make sure the edited code has the functionality described in input_spec, and passes the simulation.
The actions below are available:
<actions>
{actions}
</actions>
"""

ACTION_PROMPT = r"""
<action>
<command>{command}</command>
<signature>{signature}</signature>
<description>{description}</description>
</action>
"""

INIT_EDITION_PROMPT = r"""
The information below is give to help your work:
1. The input_spec specifing the functionality of the RTL module;
2. The generated testbench, which is verified correct by another LLM judge;
3. The generated interface expected by the testbench and RTL module;
4. The log generated by the simulation which is failed by the generated RTL and TB.
<input_spec>
{input_spec}
</input_spec>
<generated_tb>
{generated_tb}
</generated_tb>
<generated_interface>
{generated_interface}
</generated_interface>
<sim_failed_log>
{sim_failed_log}
</sim_failed_log>
{memory_context}
"""

EXTRA_ORDER_PROMPT = r"""
1. Try to understand the input_spec, locate the suspicious range, and give reasoning steps in natural language to solve the mismatchs 1 by 1.
    In addition, try to give advice to avoid syntax error.
2. For sequencial logic, carefully examine whether the signal should change when "next_state" matches, or when "state" matches.
3. For combinational logic, if encountered error with complicated multiline singal:
    Try to comment each line of the signal to avoid missing any part.
4. Don't use state_t to define the parameter. Use `localparam` or Use 'reg' or 'logic' for signals as registers or Flip-Flops.
5. DO NOT close quotes at last line before the inline comment. It would break the json syntax.
    If quote is closed before the comment, just don't add the comment.
6. Do not try to modify the testbench. Only modify the RTL code.
    Also do not try to change or define RefModule. There is RefModule defined elsewhere.
7. Always try modify RTL code as long as simulation mismatch exists, even if you think the code is correct.
    SHOW RESPECT TO THE SIMULATION RESULT.
8. Declare all ports as logic; use wire or reg for signals inside the block.
9. Not all the sequential logic need to be reset to 0 when reset is asserted,
    but these without-reset logic should be initialized to a known value with an initial block instead of being X.
10. In sequence logic, if the expected output is asserted but the dut output is not,
    carefully examine whether the input signal should affect current output (with comb logic) or next-cycle output (with seq logic).

The file content which is going to be edited is given below:
<rtl_code>
{rtl_code}
</rtl_code>
"""
# The prompt above comes from:
# @misc{ho2024verilogcoderautonomousverilogcoding,
#       title={VerilogCoder: Autonomous Verilog Coding Agents with Graph-based Planning and Abstract Syntax Tree (AST)-based Waveform Tracing Tool},
#       author={Chia-Tung Ho and Haoxing Ren and Brucek Khailany},
#       year={2024},
#       eprint={2408.08927},
#       archivePrefix={arXiv},
#       primaryClass={cs.AI},
#       url={https://arxiv.org/abs/2408.08927},
# }

SYNTAX_REPAIR_PROMPT = r"""
Route-specific repair goal: syntax-only repair.
1. Focus on compile-blocking errors such as parser errors, undeclared signals, malformed assignments, invalid procedural or continuous assignments, and missing declarations.
2. Preserve the module name, port list, port widths, and intended behavior unless a small change is required to make the RTL compile.
3. Avoid broad behavioral rewrites. Make the smallest RTL edit that removes the syntax or compile blocker.
"""

INTERFACE_REPAIR_PROMPT = r"""
Route-specific repair goal: interface-only repair.
1. Focus on module name, port names, port directions, port widths, and compatibility with the generated interface and testbench.
2. Treat generated_interface and generated_tb as the source of truth for the expected top-level module boundary.
3. Preserve internal logic as much as possible. Avoid unrelated behavior rewrites unless they are necessary to reconnect the corrected interface.
"""

LOGIC_REPAIR_PROMPT = r"""
Route-specific repair goal: logic and waveform repair.
1. Assume syntax and the top-level interface are mostly valid.
2. Use sim_failed_log to localize behavioral mismatches, timing mistakes, reset behavior issues, state transition errors, and output computation bugs.
3. Modify only the RTL logic needed to reduce or eliminate the reported mismatches.
"""

ROUTE_REPAIR_PROMPTS = {
    "generic": "",
    "syntax": SYNTAX_REPAIR_PROMPT,
    "interface": INTERFACE_REPAIR_PROMPT,
    "logic": LOGIC_REPAIR_PROMPT,
    "ambiguous_runnable": LOGIC_REPAIR_PROMPT,
}

ROUTE_ALIASES = {
    "syntax_repair": "syntax",
    "interface_repair": "interface",
    "logic_repair": "logic",
    "logic_waveform": "logic",
}

MEMORY_PROMPT = r"""
<state_checkpoint_memory>
{memory_summary}
</state_checkpoint_memory>
"""

RepairRoute = Literal[
    "generic",
    "syntax",
    "interface",
    "logic",
    "ambiguous_runnable",
]

FailureClass = Literal[
    "none",
    "syntax",
    "interface",
    "logic",
    "ambiguous_runnable",
]


SYNTAX_ERROR_PATTERNS = [
    r"\bsyntax error\b",
    r"\bmalformed statement\b",
    r"\binvalid module item\b",
    r"\binvalid port connection expression\b",
    r"\bUnable to bind wire/reg/memory\b",
    r"\bUnable to elaborate\b",
    r"\bNo function named\b",
    r"\berror: .* is not a valid l-value\b",
]

INTERFACE_ERROR_PATTERNS = [
    r"\bUnknown module type\b",
    r"\bThese modules were missing\b",
    r"\bnot a port of\b",
    r"\bPort .* expects\b",
    r"\bWrong number of ports\b",
    r"\btoo many ports\b",
    r"\btoo few ports\b",
    r"\bwidth mismatch\b",
    r"\bpruning .* high bits\b",
    r"\bpadding .* high bits\b",
]

RUNNABLE_FAILURE_PATTERNS = [
    r"\bSIMULATION FAILED\b",
    r"\bMISMATCH(?:ES)? DETECTED\b",
    r"\bFirst mismatch occurred\b",
    r"\bTimeout \d+(?:\.\d+)?s reached\b",
]

LOG_EXCERPT_MAX_CHARS = 2000


def normalize_repair_route(repair_route: str) -> RepairRoute:
    normalized_route = repair_route.strip().lower().replace("-", "_").replace("/", "_")
    normalized_route = ROUTE_ALIASES.get(normalized_route, normalized_route)
    if normalized_route in ROUTE_REPAIR_PROMPTS:
        return cast(RepairRoute, normalized_route)
    logger.warning(
        f"Unknown repair route '{repair_route}', falling back to generic repair."
    )
    return "generic"


def _decode_tool_output(tool_output: str) -> str:
    try:
        output_obj = json.loads(tool_output)
    except json.JSONDecodeError:
        return tool_output
    if not isinstance(output_obj, dict):
        return tool_output
    stdout = output_obj.get("stdout", "")
    stderr = output_obj.get("stderr", "")
    return f"{stdout}\n{stderr}".strip()


def _matches_any(patterns: List[str], text: str) -> bool:
    return any(re.search(pattern, text, flags=re.IGNORECASE) for pattern in patterns)


def compact_log_signature(log: str) -> str:
    decoded_log = _decode_tool_output(log)
    lines = [line.strip() for line in decoded_log.splitlines() if line.strip()]
    if not lines:
        return ""
    return "\n".join(lines[:12])[:1000]


def classify_debug_failure(
    *,
    is_syntax_pass: bool,
    syntax_output: str,
    is_sim_pass: bool,
    sim_mismatch_cnt: int,
    sim_output: str,
) -> FailureClass:
    if not is_syntax_pass:
        return "syntax"
    if is_sim_pass:
        return "none"

    sim_text = _decode_tool_output(sim_output)
    syntax_text = _decode_tool_output(syntax_output)
    combined_text = f"{sim_text}\n{syntax_text}"

    if _matches_any(SYNTAX_ERROR_PATTERNS, combined_text):
        return "syntax"
    if _matches_any(INTERFACE_ERROR_PATTERNS, combined_text):
        return "interface"
    if sim_mismatch_cnt > 0 or _matches_any(RUNNABLE_FAILURE_PATTERNS, combined_text):
        return "logic"
    return "ambiguous_runnable"

ACTION_OUTPUT_PROMPT = r"""
Output after running given action:
<action_output>
{action_output}
</action_output>
"""

EXAMPLE_OUTPUT = {
    "reasoning": "All reasoning steps",
    "action_input": {
        "command": "replace_content_by_matching",
        "args": {
            "old_content": "content to be replaced",
            "new_content": "content to replace",
        },
    },
}


class ActionInput(BaseModel):
    command: str
    args: Dict[str, Any]


class RTLEditorStepOutput(BaseModel):
    reasoning: str
    action_input: ActionInput


class RTLEditor:
    def __init__(
        self,
        token_counter: TokenCounter,
        sim_reviewer: SimReviewer,
    ):
        self.token_counter = token_counter
        self.history: List[ChatMessage] = []
        self.max_trials = 15
        self.succeed_history_max_length = 10
        self.fail_history_max_length = 6
        self.is_done = False
        self.last_mismatch_cnt: int | None = None
        self.last_failure_class: FailureClass | None = None
        self.last_error_signature: str = ""
        self.sim_reviewer = sim_reviewer
        self.repair_route: RepairRoute = "generic"
        self.debug_memory: DebugMemory | None = None

    def reset(self):
        self.is_done = False
        self.history = []
        self.last_mismatch_cnt: int | None = None
        self.last_failure_class = None
        self.last_error_signature = ""
        self.repair_route = "generic"
        self.debug_memory = None

    def write_rtl(self, content: str) -> None:
        with open(self.rtl_path, "w") as f:
            f.write(content)

    def read_rtl(self) -> str:
        with open(self.rtl_path, "r") as f:
            return f.read()

    def replace_sanity_check(self) -> Dict[str, Any]:
        # Run syntax check and simulation check sequentially
        is_syntax_pass, syntax_output = check_syntax(self.rtl_path)
        if is_syntax_pass:
            syntax_output = "Syntax check passed."
        if not is_syntax_pass:
            failure_class = classify_debug_failure(
                is_syntax_pass=False,
                syntax_output=syntax_output,
                is_sim_pass=False,
                sim_mismatch_cnt=0,
                sim_output="",
            )
            return {
                "is_syntax_pass": False,
                "is_sim_pass": False,
                "failure_class": failure_class,
                "error_msg": syntax_output,
                "error_signature": compact_log_signature(syntax_output),
                "sim_mismatch_cnt": 0,
            }
        is_sim_pass, sim_mismatch_cnt, sim_output = self.sim_reviewer.review()
        assert isinstance(sim_mismatch_cnt, int)
        failure_class = classify_debug_failure(
            is_syntax_pass=True,
            syntax_output=syntax_output,
            is_sim_pass=is_sim_pass,
            sim_mismatch_cnt=sim_mismatch_cnt,
            sim_output=sim_output,
        )
        return {
            "is_syntax_pass": True,
            "is_sim_pass": is_sim_pass,
            "failure_class": failure_class,
            "error_msg": "" if is_sim_pass else sim_output,
            "error_signature": compact_log_signature(sim_output),
            "sim_mismatch_cnt": sim_mismatch_cnt,
        }

    def _append_debug_history(
        self,
        *,
        action_name: str,
        action_output: Dict[str, Any],
        old_content: str,
        new_content: str,
        route_before: RepairRoute,
        route_after: RepairRoute,
    ) -> None:
        output_dir = getattr(self, "output_dir_per_run", "")
        if not output_dir:
            return
        os.makedirs(output_dir, exist_ok=True)
        record = {
            "action": action_name,
            "repair_route_before": route_before,
            "repair_route_after": route_after,
            "is_action_executed": action_output.get("is_action_executed", False),
            "acceptance_reason": action_output.get("acceptance_reason", ""),
            "is_syntax_pass": action_output.get("is_syntax_pass"),
            "is_sim_pass": action_output.get("is_sim_pass"),
            "failure_class": action_output.get("failure_class"),
            "sim_mismatch_cnt": action_output.get("sim_mismatch_cnt"),
            "error_excerpt": str(action_output.get("error_msg", ""))[
                :LOG_EXCERPT_MAX_CHARS
            ],
            "old_content_excerpt": old_content[:LOG_EXCERPT_MAX_CHARS],
            "new_content_excerpt": new_content[:LOG_EXCERPT_MAX_CHARS],
        }
        history_path = os.path.join(output_dir, "debug_history.jsonl")
        with open(history_path, "a") as f:
            f.write(json.dumps(record, sort_keys=True) + "\n")

    def _route_after_progress(self, failure_class: FailureClass) -> RepairRoute:
        if failure_class == "interface":
            return "interface"
        if failure_class in ("logic", "ambiguous_runnable"):
            return "logic"
        return self.repair_route

    def _judge_route_acceptance(
        self, action_output: Dict[str, Any]
    ) -> Tuple[bool, str, RepairRoute]:
        failure_class = cast(FailureClass, action_output["failure_class"])
        sim_mismatch_cnt = cast(int, action_output["sim_mismatch_cnt"])
        error_signature = cast(str, action_output.get("error_signature", ""))
        signature_changed = error_signature != self.last_error_signature
        route_after = self.repair_route

        if action_output["is_sim_pass"]:
            return True, "simulation passed", route_after

        if self.repair_route == "syntax":
            if failure_class in ("interface", "logic", "ambiguous_runnable"):
                route_after = self._route_after_progress(failure_class)
                return True, f"syntax repair advanced to {failure_class}", route_after
            if failure_class == "syntax" and signature_changed:
                return True, "syntax error signature changed", route_after
            return False, "syntax repair did not make observable progress", route_after

        if self.repair_route == "interface":
            if failure_class in ("logic", "ambiguous_runnable"):
                route_after = "logic"
                return True, f"interface repair advanced to {failure_class}", route_after
            if failure_class == "interface" and signature_changed:
                return True, "interface error signature changed", route_after
            return False, "interface repair did not make observable progress", route_after

        if self.repair_route in ("logic", "ambiguous_runnable"):
            if failure_class in ("syntax", "interface"):
                return False, f"logic repair introduced {failure_class} blocker", route_after
            if sim_mismatch_cnt > 0:
                if (
                    self.last_mismatch_cnt is None
                    or self.last_mismatch_cnt == 0
                    or sim_mismatch_cnt <= self.last_mismatch_cnt
                ):
                    return True, "logic mismatch count did not increase", route_after
                return False, "logic mismatch count increased", route_after
            if failure_class == "ambiguous_runnable" and signature_changed:
                return True, "ambiguous runnable failure signature changed", route_after
            return False, "logic repair did not make observable progress", route_after

        if failure_class in ("syntax", "interface"):
            return False, f"generic repair left {failure_class} blocker", route_after
        if sim_mismatch_cnt > 0 and (
            self.last_mismatch_cnt is None
            or self.last_mismatch_cnt == 0
            or sim_mismatch_cnt <= self.last_mismatch_cnt
        ):
            return True, "generic mismatch count did not increase", route_after
        if failure_class == "ambiguous_runnable" and signature_changed:
            return True, "generic ambiguous failure signature changed", route_after
        return False, "generic repair did not make observable progress", route_after

    def judge_replace_action_execution(
        self,
        old_content: str,
        new_content: str,
        action_name: str,
        old_file_content: str,
    ) -> Dict[str, Any]:
        sanity_check = self.replace_sanity_check()
        route_before = self.repair_route
        ret = {
            "is_action_executed": False,
            **sanity_check,
            "repair_route_before": route_before,
            "repair_route_after": route_before,
            "acceptance_reason": "",
        }
        if not ret["is_syntax_pass"]:
            assert isinstance(ret["error_msg"], str)
            ret["error_msg"] += (
                f"Syntax check failed. {action_name} not executed."
                f"old_content: {old_content},"
                f"new_content: {new_content}"
            )
            ret["acceptance_reason"] = "RTL syntax check failed"
            self.write_rtl(old_file_content)
            self._append_debug_history(
                action_name=action_name,
                action_output=ret,
                old_content=old_content,
                new_content=new_content,
                route_before=route_before,
                route_after=route_before,
            )
            return ret

        should_accept, acceptance_reason, route_after = self._judge_route_acceptance(
            ret
        )
        ret["acceptance_reason"] = acceptance_reason
        ret["repair_route_after"] = route_after
        if should_accept:
            # Accept replace
            logger.info(
                f"Action accepted for route {route_before}: {acceptance_reason}."
            )
            self.last_mismatch_cnt = cast(int, ret["sim_mismatch_cnt"])
            self.last_failure_class = cast(FailureClass, ret["failure_class"])
            self.last_error_signature = cast(str, ret.get("error_signature", ""))
            self.repair_route = route_after
            ret["is_action_executed"] = True
            if ret["is_sim_pass"]:
                self.is_done = True
        else:
            logger.info(
                f"Action rejected for route {route_before}: {acceptance_reason}."
            )
            self.write_rtl(old_file_content)
            assert isinstance(ret["error_msg"], str)
            ret["error_msg"] += f" {acceptance_reason}. {action_name} not executed."

        self._append_debug_history(
            action_name=action_name,
            action_output=ret,
            old_content=old_content,
            new_content=new_content,
            route_before=route_before,
            route_after=route_after,
        )

        return ret

    def replace_content_by_matching(
        self, old_content: str, new_content: str
    ) -> Dict[str, Any]:
        """
        Replace the content of the matching line in the file with the new content.
        Syntax check is performed after the replacement.
        Please ONLY replace the content that NEEDS to be modified. Don't change the content that is correct.
        Please make sure old_content only occurs once in the file.
        Input:
            old_content: The old content of the file.
            new_content: The new content to replace the matching line.
        Output:
            A dictionary containing :
                1. Whether the action is executed.
                2. The error message if the action is not executed.
                3. Other information like syntax check result and simulation check result.
        Example:
            Before:
            <example_rtl>
                1 module test;
                2   reg a;
                3   reg b;
                4 endmodule
            </example_rtl>
            Action:
            <action_input>
                "command": "replace_content_by_matching",
                "args": {
                    "old_content": "  reg a;\n  reg b;",
                    "new_content": "  logic a;",
                },
            </action_input>
            Now:
            <example_rtl>
                1 module test;
                2   logic a;
                4 endmodule
            </example_rtl>
        """
        old_file_content = self.read_rtl().expandtabs(4)
        old_content = old_content.expandtabs(4)
        new_content = new_content.expandtabs(4)

        # Check if old_str is unique in the file
        logger.info(f"Old File Content:")
        logger.info(old_file_content)
        logger.info(f"Target old Content:")
        logger.info(old_content)
        logger.info(f"Target new Content:")
        logger.info(new_content)
        occurrences = old_file_content.count(old_content)
        if occurrences == 0:
            ret = {
                "is_action_executed": False,
                "new_content": "",
                "error_msg": f"Cannot find old_content in current RTL. replace_content_by_matching not executed.",
                "acceptance_reason": "old_content not found",
                "repair_route_before": self.repair_route,
                "repair_route_after": self.repair_route,
            }
            self._append_debug_history(
                action_name="replace_content_by_matching",
                action_output=ret,
                old_content=old_content,
                new_content=new_content,
                route_before=self.repair_route,
                route_after=self.repair_route,
            )
            return ret
        elif occurrences > 1:
            ret = {
                "is_action_executed": False,
                "new_content": "",
                "error_msg": f"Find multiple old_content in current RTL. replace_content_by_matching not executed.",
                "acceptance_reason": "old_content matched multiple locations",
                "repair_route_before": self.repair_route,
                "repair_route_after": self.repair_route,
            }
            self._append_debug_history(
                action_name="replace_content_by_matching",
                action_output=ret,
                old_content=old_content,
                new_content=new_content,
                route_before=self.repair_route,
                route_after=self.repair_route,
            )
            return ret

        # Replace old_str with new_str
        new_file_content = old_file_content.replace(old_content, new_content)
        self.write_rtl(new_file_content)
        ret = self.judge_replace_action_execution(
            old_content, new_content, "replace_content_by_matching", old_file_content
        )
        # ret["new_file_content"] = new_file_content
        return ret

    def generate(self, messages: List[ChatMessage]) -> ChatResponse:
        logger.info(f"RTL editor input message: {messages}")
        resp, token_cnt = self.token_counter.count_chat(messages)
        logger.info(f"Token count: {token_cnt}")
        logger.info(f"{resp.message.content}")
        return resp

    def gen_action_prompt(self, function) -> str:
        return ACTION_PROMPT.format(
            command=function.__name__,
            signature=signature(function),
            description=function.__doc__,
        )

    def get_init_prompt_messages(self) -> List[ChatMessage]:
        actions = [self.replace_content_by_matching]
        actions_prompt = SYSTEM_PROMPT.format(
            actions="".join([self.gen_action_prompt(action) for action in actions])
        )
        system_prompt = ChatMessage(content=actions_prompt, role=MessageRole.SYSTEM)
        with open(self.tb_path, "r") as f:
            generated_tb = f.read()
        try:
            with open(self.if_path, "r") as f:
                generated_interface = f.read()
        except FileNotFoundError:
            generated_interface = "No generated interface file found."
        memory_summary = (
            self.debug_memory.format_for_prompt()
            if self.debug_memory is not None
            else None
        )
        memory_context = (
            MEMORY_PROMPT.format(memory_summary=memory_summary)
            if memory_summary
            else ""
        )
        edit_init_prompt = ChatMessage(
            content=INIT_EDITION_PROMPT.format(
                input_spec=self.spec,
                generated_tb=generated_tb,
                generated_interface=generated_interface,
                sim_failed_log=self.sim_failed_log,
                memory_context=memory_context,
            ),
            role=MessageRole.USER,
        )
        ret = [system_prompt, edit_init_prompt]
        if (
            isinstance(self.token_counter, TokenCounterCached)
            and self.token_counter.enable_cache
        ):
            self.token_counter.add_cache_tag(ret[-1])
        return ret

    def get_order_prompt_messages(self) -> List[ChatMessage]:
        with open(self.rtl_path, "r") as f:
            rtl_code = f.read()

        logger.info(f"----------> RTLEDITOR RECEIVED ROUTE: {self.repair_route}")
        route_prompt = ROUTE_REPAIR_PROMPTS[self.repair_route]
        memory_context = (
            "\n"
            + MEMORY_PROMPT.format(
                memory_summary=self.debug_memory.format_for_prompt()
            )
            if self.debug_memory is not None
            else ""
        )
        return [
            ChatMessage(
                content=ORDER_PROMPT.format(
                    output_format="".join(json.dumps(EXAMPLE_OUTPUT, indent=4))
                )
                + EXTRA_ORDER_PROMPT.format(rtl_code=rtl_code)
                + f"\nCurrent repair_route: {self.repair_route}\n"
                + route_prompt
                + memory_context,
                role=MessageRole.USER,
            ),
        ]

    def parse_output(self, response: ChatResponse) -> RTLEditorStepOutput:
        content = reformat_json_string(response.message.content)
        output_json_obj: Dict = json.loads(content, strict=False)
        action_input = output_json_obj["action_input"]
        command = action_input["command"]

        args = action_input["args"]
        return RTLEditorStepOutput(
            reasoning=output_json_obj["reasoning"],
            action_input=ActionInput(command=command, args=args),
        )

    def run_action(self, action_input: ActionInput) -> Dict[str, Any]:
        logger.info(f"Action input: {action_input}")
        action = getattr(self, action_input.command)
        action_output = action(**action_input.args)
        logger.info(f"Action output: {action_output}")
        return action_output

    def record_action_checkpoint(
        self,
        round_index: int,
        action_input: ActionInput,
        action_output: Dict[str, Any],
    ) -> None:
        if self.debug_memory is None:
            return
        try:
            rtl_code = self.read_rtl()
        except FileNotFoundError:
            rtl_code = ""
        action_summary = json.dumps(action_input.model_dump(), indent=2)
        notes = json.dumps(
            {
                "is_action_executed": action_output.get("is_action_executed"),
                "acceptance_reason": action_output.get("acceptance_reason", ""),
                "repair_route_before": action_output.get("repair_route_before"),
                "repair_route_after": action_output.get("repair_route_after"),
                "failure_class": action_output.get("failure_class"),
            },
            indent=2,
        )
        self.debug_memory.add_checkpoint(
            stage=f"rtl_editor_action_{round_index}",
            rtl_code=rtl_code,
            sim_log=str(action_output.get("error_msg", "")),
            is_syntax_pass=action_output.get("is_syntax_pass"),
            is_sim_pass=action_output.get("is_sim_pass"),
            mismatch_count=action_output.get("sim_mismatch_cnt"),
            action=action_summary,
            notes=notes,
        )

    def get_action_output_message(self, output: Dict[str, Any]) -> List[ChatMessage]:
        return [
            ChatMessage(
                content=ACTION_OUTPUT_PROMPT.format(
                    action_output=json.dumps(output, indent=4)
                ),
                role=MessageRole.USER,
            ),
        ]

    def chat(
        self,
        spec: str,
        output_dir_per_run: str,
        sim_failed_log: str,
        sim_mismatch_cnt: int,
        repair_route: str = "generic",
        debug_memory: DebugMemory | None = None,
    ) -> Tuple[bool, str]:
        # 1. Initialize the history
        # 2. Generate the initial prompt messages (with functool information)
        # 3. Loop for the max trials:
        #     - Generate the order prompt messages
        #     - Generate & parse the response
        #     - Generate & parse the tool call
        #     - If called
        if isinstance(self.token_counter, TokenCounterCached):
            self.token_counter.set_enable_cache(True)
        self.history = []
        self.token_counter.set_cur_tag(self.__class__.__name__)
        self.spec = spec
        self.output_dir_per_run = output_dir_per_run
        self.tb_path = f"{output_dir_per_run}/tb.sv"
        self.if_path = f"{output_dir_per_run}/if.sv"
        self.rtl_path = f"{output_dir_per_run}/rtl.sv"
        self.sim_failed_log = sim_failed_log
        self.last_mismatch_cnt = sim_mismatch_cnt
        self.repair_route = normalize_repair_route(repair_route)
        self.debug_memory = debug_memory
        self.last_failure_class = (
            self.repair_route
            if self.repair_route
            in ("syntax", "interface", "logic", "ambiguous_runnable")
            else None
        )
        self.last_error_signature = compact_log_signature(sim_failed_log)

        self.history.extend(self.get_init_prompt_messages())
        is_pass = False
        succeed_history: List[ChatMessage] = []
        fail_history: List[ChatMessage] = []
        for i in range(self.max_trials):
            logger.info(f"RTL Editing: round {i + 1} / {self.max_trials}")
            response = self.generate(
                self.history
                + succeed_history
                + fail_history
                + self.get_order_prompt_messages()
            )
            new_contents = [response.message]
            action_input = self.parse_output(response).action_input
            action_output = self.run_action(action_input)
            self.record_action_checkpoint(i + 1, action_input, action_output)
            if self.is_done:
                is_pass = True
                break
            new_contents.extend(self.get_action_output_message(action_output))
            assert len(new_contents) == 2, f"new_contents: {new_contents}"
            if action_output["is_action_executed"]:
                fail_history = []
                succeed_history.extend(new_contents)
                if len(succeed_history) > self.succeed_history_max_length:
                    succeed_history = succeed_history[
                        -self.succeed_history_max_length :
                    ]
            else:
                fail_history.extend(new_contents)
                if len(fail_history) > self.fail_history_max_length:
                    fail_history = fail_history[-self.fail_history_max_length :]

        with open(self.rtl_path, "r") as f:
            rtl_code = f.read()
        return (is_pass, rtl_code)
