import json
from typing import Dict, List

from llama_index.core.base.llms.types import ChatMessage, ChatResponse, MessageRole
from pydantic import BaseModel

from .log_utils import get_logger
from .prompts import ORDER_PROMPT
from .token_counter import TokenCounter, TokenCounterCached
from .utils import add_lineno, reformat_json_string

logger = get_logger(__name__)

SYSTEM_PROMPT = r"""
You are an expert in SystemVerilog design.
You can always write SystemVerilog code with no syntax errors and always reach correct functionality.
"""

GENERATION_PROMPT = r"""
A simulation has failed for the rtl and testbench generated by other agents;
The related failed_sim_log was given below. The input_spec which the rtl and testbench should follow was also given below.
Please judge whether the TESTBENCH need to be modified.
If you think so, set tb_needs_fix = True, otherwise set tb_needs_fix = False.
{tb_fix_policy}

If tb_needs_fix is False, you MUST categorize the RTL failure into one of the three error routes based on the sim_log:
- "syntax": Compile errors, parser errors, undeclared signals.
- "interface": Port width mismatches, missing ports, module name mismatches.
- "logic": The code compiles, but simulation fails or outputs mismatch.
Set error_route to "syntax", "interface" , or "logic".

Try to understand the requirements above and give reasoning steps in natural language to achieve it.

<input_spec>
{input_spec}
</input_spec>
<failed_sim_log>
{failed_sim_log}
</failed_sim_log>
{memory_context}
<failed_rtl>
{failed_rtl}
</failed_rtl>
<failed_testbench>
{failed_testbench}
</failed_testbench>
"""

EXAMPLE_OUTPUT = {
    "reasoning": "All reasoning steps",
    "tb_needs_fix": False,
    "error_route": "logic",
}


class TBOutputFormat(BaseModel):
    reasoning: str
    tb_needs_fix: bool
    error_route: str


TB_FIX_ALLOWED_ORDER_PROMPT = r"""
Especially, FORCE SET tb_needs_fix to True if failed_sim_log says there is ANY syntax error in testbench(tb.sv),
Even if the syntax error looks not related to the failed test case or the testbench looks correct.
"""

TB_FIX_FORBIDDEN_POLICY_PROMPT = r"""

IMPORTANT: This run uses a golden benchmark oracle: the testbench and/or RefModule
are treated as authoritative ground truth for pass/fail. Do NOT decide that the
testbench or RefModule should be modified, even if the natural language spec
appears to disagree with the reference behavior. Set tb_needs_fix to False and
route the failure to the RTL debugger.
"""

TB_FIX_FORBIDDEN_ORDER_PROMPT = r"""
Because this run uses a golden benchmark oracle, you MUST set tb_needs_fix to False.
Do not ask to modify the testbench or RefModule. Classify the RTL failure route as
"syntax", "interface", or "logic" from the compile/simulation log.
"""

VALID_ERROR_ROUTES = {"syntax", "interface", "logic"}

MEMORY_PROMPT = r"""
<state_checkpoint_memory>
{memory_summary}
</state_checkpoint_memory>
"""


class SimJudge:
    def __init__(
        self,
        token_counter: TokenCounter,
    ):
        self.token_counter = token_counter
        self.history: List[ChatMessage] = []

    def reset(self):
        self.history = []

    def generate(self, messages: List[ChatMessage]) -> ChatResponse:
        logger.info(f"Sim judge input message: {messages}")
        resp, token_cnt = self.token_counter.count_chat(messages)
        logger.info(f"Token count: {token_cnt}")
        logger.info(f"{resp.message.content}")
        return resp

    def get_init_prompt_messages(
        self,
        input_spec: str,
        failed_sim_log: str,
        failed_rtl: str,
        failed_testbench: str,
        allow_tb_fix: bool,
        memory_summary: str | None = None,
    ) -> List[ChatMessage]:
        tb_fix_policy = "" if allow_tb_fix else TB_FIX_FORBIDDEN_POLICY_PROMPT
        memory_context = (
            MEMORY_PROMPT.format(memory_summary=memory_summary)
            if memory_summary
            else ""
        )
        ret = [
            ChatMessage(content=SYSTEM_PROMPT, role=MessageRole.SYSTEM),
            ChatMessage(
                content=GENERATION_PROMPT.format(
                    input_spec=input_spec,
                    failed_sim_log=failed_sim_log,
                    memory_context=memory_context,
                    failed_rtl=add_lineno(failed_rtl),
                    failed_testbench=add_lineno(failed_testbench),
                    tb_fix_policy=tb_fix_policy,
                ),
                role=MessageRole.USER,
            ),
        ]
        return ret

    def get_order_prompt_messages(self, allow_tb_fix: bool) -> List[ChatMessage]:
        extra_order_prompt = (
            TB_FIX_ALLOWED_ORDER_PROMPT
            if allow_tb_fix
            else TB_FIX_FORBIDDEN_ORDER_PROMPT
        )
        return [
            ChatMessage(
                content=ORDER_PROMPT.format(
                    output_format="".join(json.dumps(EXAMPLE_OUTPUT, indent=4))
                    + extra_order_prompt
                ),
                role=MessageRole.USER,
            ),
        ]

    def parse_output(self, response: ChatResponse) -> TBOutputFormat:
        content = reformat_json_string(response.message.content)
        output_json_obj: Dict = json.loads(content, strict=False)
        return TBOutputFormat(
            reasoning=output_json_obj["reasoning"],
            tb_needs_fix=output_json_obj["tb_needs_fix"],
            error_route=output_json_obj.get("error_route", "logic")
        )

    def chat(
        self,
        input_spec: str,
        failed_sim_log: str,
        failed_rtl: str,
        failed_testbench: str,
        allow_tb_fix: bool = True,
        memory_summary: str | None = None,
    ) -> tuple[bool, str]:
        if isinstance(self.token_counter, TokenCounterCached):
            self.token_counter.set_enable_cache(False)
        self.history = []
        self.token_counter.set_cur_tag(self.__class__.__name__)
        self.history.extend(
            self.get_init_prompt_messages(
                input_spec,
                failed_sim_log,
                failed_rtl,
                failed_testbench,
                allow_tb_fix,
                memory_summary,
            )
        )
        self.history.extend(self.get_order_prompt_messages(allow_tb_fix))
        response = self.generate(self.history)
        resp_obj = self.parse_output(response)
        if resp_obj.error_route not in VALID_ERROR_ROUTES:
            logger.warning(
                f"Unknown judge error_route '{resp_obj.error_route}', falling back to logic."
            )
            resp_obj.error_route = "logic"
        if not allow_tb_fix and resp_obj.tb_needs_fix:
            logger.info(
                "Golden oracle mode forbids testbench repair; forcing tb_needs_fix=False."
            )
            resp_obj.tb_needs_fix = False
        logger.info(f"JUDGE AGENT ERROR ROUTE = {resp_obj.error_route}")
        return resp_obj.tb_needs_fix, resp_obj.error_route
